### ISSUE TITLE
Tools appears to re-auth for every related record type (50+), eventually failing to sign in

### ISSUE THREAD

**Issue by strikeir13** [rappen/RelatedRecordsAnalyzer#16]
I tried to use the Related Records Analyzer today and it seemed to need to re-authenticate for every different related record type. Here is what happened multiple times today:

1. Open XrmToolBox
2. Connect to target environment
3. Launch Related Records Analyzer
4. Select entity (Project from PSA Suite), get message about number of records exceeding Quick View, click OK to ignore
5. Enter URL for Project to be analyzed, URL is resolved successfully
6. Click Analyze Relations
7. The tool goes through about 6 related record types normally but then starts popping up an authentication box where it seems to re-sign in again. The next 3 record types have the auth dialog appear but the re-sign-in appears to happen successfully without any user interaction. After that, though, it shows the following dialog for EVERY subsequent record type. This makes the tool unusable because there are often 50-70+ record types being analyzed, and clicking through this dialog that many times is not feasible.
![image](https://github.com/user-attachments/assets/9c5d2b38-d69e-4092-9178-9177fa49cc4b)
Even after closing the Related Records tool tab in XrmToolBox, the sign-in dialog keeps showing up and the only way to get it to stop is to end the XrmToolBox task via Windows Task Manager.

This is the version of the Related Records Analyzer I'm using:
![image](https://github.com/user-attachments/assets/66f6db57-8f3c-4904-b033-46301008e87f)

This is the version of XrmToolBox I'm using:
![image](https://github.com/user-attachments/assets/147a8f1a-3a81-4fa0-adea-4d70128a6d3d)

**Comment by rappen** [comment]
I've got that issue myself... Annoying as f!

So it's on my list to fix this. I don't really know why/when it occurs, but I have fixed (or worked around it) by using another type of connection, going from Wizard to OAuth.

![image](https://github.com/user-attachments/assets/2e0b846c-2349-4547-a509-9cd03ff8a711)

**Comment by strikeir13** [comment]
Swapped to OAuth and it worked normally. Thanks!

**Comment by rappen** [comment]
Great to hear!
I'm closing this issue now.
